import os
from dataclasses import asdict

from tqdm import tqdm

from geo_vlms.backends import Backend
from geo_vlms.example import Example
from geo_vlms.runs import RecordWriter


def run_inference(
    examples: list[Example],
    backend: Backend,
    out_path: str | os.PathLike,
    model_name: str,
    progress: bool = True,
    max_new_tokens: int = 64,
    append: bool = False,
    top_logprobs: int | None = None,
) -> list[dict]:
    """
    Run the VLM over a list of examples and write the raw outputs to disk.

    Args:
        examples: The examples to run.
        model: The VLM model.
        processor: The processor associated with the model.
        out_path: Path to the output `.jsonl`, one record per example.
        model_name: The model's HuggingFace name, recorded for provenance.
        progress: Whether to show a progress bar during inference.
        max_new_tokens: Max tokens that can be generated by the model.
        append: Whether or not to append to an output file instead of overwriting.
        top_logprobs: Alternatives to record per generated token; None skips logprobs.

    Returns:
        The records corresponding to the examples.
    """
    records = []
    with RecordWriter(out_path, append=append) as writer:
        pbar = (
            examples
            if not progress
            else tqdm(
                examples, ncols=120, total=len(examples), desc="Running Inference."
            )
        )
        for example in pbar:
            # A None image_path means a text-only control: pass no images
            # rather than a list containing None.
            images = None if example.image_path is None else [example.image_path]
            generation = backend.generate(
                prompt=example.prompt,
                images=images,
                max_new_tokens=max_new_tokens,
                top_logprobs=top_logprobs,
            )
            record = asdict(example) | {
                "output": generation.text,
                "model_name": model_name,
                "prompt_tokens": generation.prompt_tokens,
                "completion_tokens": generation.completion_tokens,
                "latency_s": generation.latency_s,
            }
            if generation.tokens is not None:
                record["tokens"] = [asdict(t) for t in generation.tokens]

            writer.write(record)
            records.append(record)

    return records
