import json
import os
from dataclasses import asdict

from tqdm import tqdm

from geo_vlms.backends import Backend
from geo_vlms.example import Example


def run_inference(
    examples: list[Example],
    backend: Backend,
    out_path: str | os.PathLike,
    model_name: str,
    progress: bool = True,
    max_new_tokens: int = 64,
    append: bool = False,
) -> list[dict]:
    """
    Run the VLM over a list of examples and write the raw outputs to disk.

    Args:
        examples: The examples to run.
        model: The VLM model.
        processor: The processor associated with the model.
        out_path: Path to the output `.jsonl`, one record per example.
        model_name: The model's HuggingFace name, recorded for provenance.
        progress: Whether to show a progress bar during inference.
        max_new_tokens: Max tokens that can be generated by the model.
        append: Whether or not to append to an output file instead of overwriting.

    Returns:
        The records corresponding to the examples.
    """
    records = []
    f_mode = "a" if append else "w"
    with open(out_path, f_mode) as f:
        pbar = (
            examples
            if not progress
            else tqdm(
                examples, ncols=120, total=len(examples), desc="Running Inference."
            )
        )
        for example in pbar:
            # A None image_path means a text-only control: pass no images
            # rather than a list containing None.
            image_paths = None if example.image_path is None else [example.image_path]
            output = backend.generate(
                prompt=example.prompt,
                image_paths=image_paths,
                max_new_tokens=max_new_tokens,
            )
            record = asdict(example) | {"output": output, "model_name": model_name}

            # Flush per record so a mid-run crash still leaves the completed
            # examples on disk.
            f.write(json.dumps(record) + "\n")
            f.flush()

            records.append(record)

    return records
